# Generated by Django 5.0.6 on 2024-10-28 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parentguardian',
            name='user',
            field=models.OneToOneField(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentguardian',
            name='email',
            field=models.EmailField(default='sam@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
