# Generated by Django 5.0.6 on 2024-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_parentguardian_user_alter_parentguardian_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentstudentrelationship',
            name='relation_type',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('guardian', 'Guardian'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='parentstudentrelationship',
            unique_together={('student', 'parent_guardian')},
        ),
    ]
