# Generated by Django 5.0.6 on 2024-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_parentstudentrelationship_relation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentguardian',
            name='parent_id',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
