# Generated by Django 5.0.6 on 2024-11-15 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_schoolregistration_landingpage_short_c_e4d8f6_idx_and_more'),
        ('students', '0004_parentguardian_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentguardian',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='landingpage.schoolregistration'),
            preserve_default=False,
        ),
    ]
