# Generated by Django 5.0.6 on 2024-11-25 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_session_school_and_more'),
        ('classes', '0013_arm_classes_arm_name_36696c_idx_and_more'),
        ('schools', '0004_branch_schools_bra_branch__6b913a_idx_and_more'),
        ('students', '0005_parentguardian_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='guardians',
        ),
        migrations.AddField(
            model_name='student',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to='academics.session'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_session'], name='students_st_current_d93a24_idx'),
        ),
    ]
