# Generated by Django 5.0.6 on 2024-11-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_guardians_student_current_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(related_name='students', through='students.ParentStudentRelationship', to='students.parentguardian'),
        ),
    ]
