# Generated by Django 5.0.6 on 2024-08-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_class_branches_class_level_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='base_code',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
