# Generated by Django 5.0.6 on 2024-08-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_subject_base_code_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='all_levels',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary')], max_length=20),
        ),
    ]
