# Generated by Django 5.0.6 on 2024-08-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_subjecttype_rename_all_levels_subject_is_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default=1, editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code_prefix',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
