# Generated by Django 5.0.6 on 2024-08-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_subject_subject_code_subject_subject_code_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code_prefix',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
