# Generated by Django 5.0.6 on 2024-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_subject_subject_code_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AddField(
            model_name='subject',
            name='departments',
            field=models.ManyToManyField(blank=True, to='classes.department'),
        ),
        migrations.AddField(
            model_name='subjecttype',
            name='level',
            field=models.CharField(choices=[('creche', 'Creche'), ('kindergarten', 'Kindergarten'), ('nursery', 'Nursery'), ('lower_primary', 'Lower Primary'), ('upper_primary', 'Upper Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary'), ('general_primary', 'General Primary'), ('general_secondary', 'General Secondary')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('creche', 'Creche'), ('kindergarten', 'Kindergarten'), ('nursery', 'Nursery'), ('primary', 'Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary')], max_length=20),
        ),
    ]
