# Generated by Django 5.0.6 on 2024-08-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_remove_subject_department_subject_departments_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teachers',
            field=models.ManyToManyField(blank=True, related_name='class_teacher_of', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('creche', 'Creche'), ('kindergarten', 'Kindergarten'), ('nursery', 'Nursery'), ('upper_primary', 'Upper Primary'), ('lower_primary', 'Lower Primary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary')], max_length=20),
        ),
        migrations.CreateModel(
            name='TeacherSubjectClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_assigned', models.ManyToManyField(related_name='teacher_subject_classes', to='classes.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='classes.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_class_assignments', to='staff.staff')),
            ],
            options={
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
