# Generated by Django 5.0.6 on 2024-08-24 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_class_class_teachers_alter_class_level_and_more'),
        ('schools', '0003_remove_branch_classes'),
        ('staff', '0002_staff_status_alter_staff_cv_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubjectclassassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachersubjectclassassignment',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='schools.branch'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectclassassignment',
            unique_together={('teacher', 'subject', 'branch')},
        ),
    ]
