# Generated by Django 5.0.6 on 2024-09-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_alter_teachersubjectclassassignment_unique_together_and_more'),
        ('schools', '0004_branch_schools_bra_branch__6b913a_idx_and_more'),
        ('staff', '0003_role_staff_role_name_6a1dfc_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='arm',
            index=models.Index(fields=['name'], name='classes_arm_name_36696c_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['name'], name='classes_cla_name_397963_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['level'], name='classes_cla_level_6d5707_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['department'], name='classes_cla_departm_7c328c_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='classes_dep_name_4b9b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='classes_sub_name_5622bf_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_code'], name='classes_sub_subject_2717b1_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_type'], name='classes_sub_subject_35253d_idx'),
        ),
        migrations.AddIndex(
            model_name='subjecttype',
            index=models.Index(fields=['name'], name='classes_sub_name_d17246_idx'),
        ),
        migrations.AddIndex(
            model_name='subjecttype',
            index=models.Index(fields=['level'], name='classes_sub_level_bb2ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectclassassignment',
            index=models.Index(fields=['teacher'], name='classes_tea_teacher_f28f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectclassassignment',
            index=models.Index(fields=['subject'], name='classes_tea_subject_180797_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectclassassignment',
            index=models.Index(fields=['branch'], name='classes_tea_branch__c36346_idx'),
        ),
    ]
