# Generated by Django 5.0.6 on 2024-11-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_session_school_and_more'),
        ('classes', '0013_arm_classes_arm_name_36696c_idx_and_more'),
        ('schools', '0004_branch_schools_bra_branch__6b913a_idx_and_more'),
        ('staff', '0003_role_staff_role_name_6a1dfc_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachersubjectclassassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachersubjectclassassignment',
            name='session',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachersubjectclassassignment',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.term'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teachersubjectclassassignment',
            unique_together={('teacher', 'subject', 'branch', 'session', 'term')},
        ),
        migrations.AddIndex(
            model_name='teachersubjectclassassignment',
            index=models.Index(fields=['session'], name='classes_tea_session_ffa88d_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubjectclassassignment',
            index=models.Index(fields=['term'], name='classes_tea_term_id_a789d2_idx'),
        ),
    ]
