# Generated by Django 5.0.6 on 2024-11-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_session_school_and_more'),
        ('classes', '0014_alter_teachersubjectclassassignment_unique_together_and_more'),
        ('schools', '0004_branch_schools_bra_branch__6b913a_idx_and_more'),
        ('staff', '0003_role_staff_role_name_6a1dfc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_classes', models.ManyToManyField(blank=True, null=True, related_name='teacher_assignments', to='classes.class')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_assignments', to='schools.branch')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_assignments', to='academics.session')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='staff.staff')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_class_assignments', to='academics.term')),
            ],
            options={
                'indexes': [models.Index(fields=['teacher'], name='classes_tea_teacher_cd2b81_idx'), models.Index(fields=['session'], name='classes_tea_session_04334c_idx'), models.Index(fields=['term'], name='classes_tea_term_id_5e6fb4_idx'), models.Index(fields=['branch'], name='classes_tea_branch__578d91_idx')],
                'unique_together': {('teacher', 'session', 'term', 'branch')},
            },
        ),
    ]
