# Generated by Django 5.0.6 on 2024-07-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('school_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('theme', models.CharField(choices=[('theme1', 'Theme 1'), ('theme2', 'Theme 2')], max_length=100)),
                ('admin_first_name', models.CharField(max_length=100)),
                ('admin_last_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_phone_number', models.CharField(max_length=15)),
                ('referral_source', models.CharField(max_length=255)),
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
