# Generated by Django 5.0.6 on 2024-07-16 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('short_code', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('theme_color1', models.CharField(max_length=7)),
                ('theme_color2', models.CharField(max_length=7)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('admin_phone_number', models.CharField(max_length=15)),
                ('referral_source', models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('google', 'Google'), ('youtube', 'YouTube'), ('x', 'X')], default='other', max_length=50)),
                ('school_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
