# Generated by Django 5.0.6 on 2024-09-06 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['short_code'], name='landingpage_short_c_e4d8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['school_name'], name='landingpage_school__162e81_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['state'], name='landingpage_state_f52f54_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['lga'], name='landingpage_lga_45ca56_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['email'], name='landingpage_email_2b2dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['admin_user'], name='landingpage_admin_u_3c62fb_idx'),
        ),
    ]
