# Generated by Django 5.0.6 on 2024-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolregistration',
            name='city',
            field=models.CharField(default='otta', max_length=100),
            preserve_default=False,
        ),
    ]
