# Generated by Django 5.0.6 on 2024-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_schoolregistration_landingpage_short_c_e4d8f6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolregistration',
            name='logo',
            field=models.ImageField(default='https://res.cloudinary.com/<cloud_name>/image/upload/v123456789/default.jpg', upload_to='logos'),
        ),
    ]
