# Generated by Django 5.0.6 on 2025-02-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_alter_schoolregistration_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolregistration',
            name='admin_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
