# Generated by Django 5.0.6 on 2024-09-06 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_branch_schools_bra_branch__6b913a_idx_and_more'),
        ('staff', '0002_staff_status_alter_staff_cv_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='staff_role_name_6a1dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['user'], name='staff_staff_user_id_32b4ab_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['role'], name='staff_staff_role_id_d32aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['gender'], name='staff_staff_gender_f98792_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['marital_status'], name='staff_staff_marital_f2696a_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['status'], name='staff_staff_status_8fcdd8_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['phone_number'], name='staff_staff_phone_n_b40ec1_idx'),
        ),
    ]
