# Generated by Django 5.0.6 on 2024-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_role_staff_role_name_6a1dfc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
