# Generated by Django 5.0.6 on 2025-01-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_account_name_staff_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Enter the staff's salary", max_digits=10, null=True),
        ),
    ]
