# Generated by Django 5.0.6 on 2024-12-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_session_school_and_more'),
        ('comments', '0003_alter_comment_unique_together'),
        ('students', '0007_student_guardians'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('student', 'session', 'term')},
        ),
    ]
