# Generated by Django 5.0.6 on 2024-12-02 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_session_school_and_more'),
        ('schools', '0004_branch_schools_bra_branch__6b913a_idx_and_more'),
        ('students', '0007_student_guardians'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField(auto_now_add=True)),
                ('punctuality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attentiveness', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('obedience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('leadership', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.branch')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.session')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_ratings', to='students.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='PsychomotorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField(auto_now_add=True)),
                ('coordination', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('handwriting', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sports', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('music', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.branch')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.session')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychomotor_ratings', to='students.student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
        ),
    ]
