# Generated by Django 5.0.6 on 2024-12-03 23:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_session_school_and_more'),
        ('ratings', '0005_alter_behavioralrating_attentiveness_and_more'),
        ('schools', '0004_branch_schools_bra_branch__6b913a_idx_and_more'),
        ('students', '0007_student_guardians'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychomotorrating',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='psychomotorrating',
            name='session',
        ),
        migrations.RemoveField(
            model_name='psychomotorrating',
            name='student',
        ),
        migrations.RemoveField(
            model_name='psychomotorrating',
            name='term',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('psychomotor', 'Psychomotor'), ('behavioral', 'Behavioral')], default='psychomotor', max_length=15)),
                ('rating_date', models.DateField(auto_now_add=True)),
                ('coordination', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('handwriting', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('sports', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('artistry', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('verbal_fluency', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('games', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('punctuality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('attentiveness', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('obedience', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('leadership', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('emotional_stability', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('teamwork', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.branch')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.term')),
            ],
        ),
        migrations.DeleteModel(
            name='BehavioralRating',
        ),
        migrations.DeleteModel(
            name='PsychomotorRating',
        ),
    ]
