# Generated by Django 5.0.6 on 2024-12-05 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_remove_psychomotorrating_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='neatness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
