# Generated by Django 5.0.6 on 2025-01-01 21:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_session_session_name_and_more'),
        ('landingpage', '0003_alter_schoolregistration_logo'),
        ('ratings', '0007_rating_neatness'),
        ('schools', '0004_branch_schools_bra_branch__6b913a_idx_and_more'),
        ('students', '0007_student_guardians'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='artistry',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='attentiveness',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='coordination',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='emotional_stability',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='games',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='handwriting',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='neatness',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='obedience',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='punctuality',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='sports',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='teamwork',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='verbal_fluency',
        ),
        migrations.AddField(
            model_name='rating',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.branch'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_type',
            field=models.CharField(blank=True, choices=[('psychomotor', 'Psychomotor'), ('behavioral', 'Behavioral')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.session'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='students.student'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.term'),
        ),
        migrations.CreateModel(
            name='RatingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(blank=True, choices=[('psychomotor', 'Psychomotor'), ('behavioral', 'Behavioral')], max_length=15, null=True)),
                ('criteria_name', models.CharField(blank=True, max_length=50, null=True)),
                ('max_value', models.PositiveSmallIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_criteria', to='schools.branch')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_criteria', to='landingpage.schoolregistration')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ratings.ratingcriteria'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['student', 'session', 'term'], name='ratings_rat_student_33ca1b_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['branch', 'rating_type'], name='ratings_rat_branch__c27de5_idx'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('student', 'session', 'term', 'branch', 'criteria'), name='unique_rating_per_student'),
        ),
        migrations.AddIndex(
            model_name='ratingcriteria',
            index=models.Index(fields=['school', 'branch'], name='ratings_rat_school__d36fca_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingcriteria',
            index=models.Index(fields=['rating_type'], name='ratings_rat_rating__45c72e_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratingcriteria',
            constraint=models.UniqueConstraint(fields=('school', 'branch', 'rating_type', 'criteria_name'), name='unique_rating_criteria_per_branch'),
        ),
    ]
