# Generated by Django 5.0.6 on 2024-07-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landingpage', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimarySchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pry_school_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('school_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(default='default.jpeg', upload_to='logos')),
                ('address', models.CharField(max_length=255)),
                ('parent_school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_school', to='landingpage.schoolregistration')),
                ('secondary_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_schools', to='landingpage.schoolregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='landingpage.schoolregistration')),
                ('primary_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_branches', to='schools.primaryschool')),
            ],
        ),
    ]
