# Generated by Django 5.0.6 on 2024-08-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_class_branches_class_level_subject_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='branches', to='classes.class'),
        ),
    ]
