# Generated by Django 5.0.6 on 2024-08-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_branch_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='classes',
        ),
    ]
