# Generated by Django 5.0.6 on 2024-07-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='admin',
        ),
    ]
