# Generated by Django 5.0.6 on 2024-11-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(editable=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['session_name'], name='academics_s_session_3c1bae_idx'), models.Index(fields=['is_active'], name='academics_s_is_acti_5f0152_idx')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.session')),
            ],
            options={
                'indexes': [models.Index(fields=['term_name'], name='academics_t_term_na_3c2ad8_idx'), models.Index(fields=['session'], name='academics_t_session_fd134d_idx')],
                'unique_together': {('term_name', 'session')},
            },
        ),
    ]
