# Generated by Django 5.0.6 on 2024-11-24 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('landingpage', '0002_schoolregistration_landingpage_short_c_e4d8f6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='landingpage.schoolregistration'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['school'], name='academics_s_school__c90828_idx'),
        ),
    ]
