# Generated by Django 5.0.6 on 2024-12-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_session_school_and_more'),
        ('landingpage', '0003_alter_schoolregistration_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('school', 'session_name')},
        ),
    ]
