# Generated by Django 5.0.6 on 2024-12-01 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_session_school_and_more'),
        ('schools', '0004_branch_schools_bra_branch__6b913a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDaysOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_open', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_open_records', to='schools.branch')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_open_records', to='academics.session')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_open_records', to='academics.term')),
            ],
            options={
                'indexes': [models.Index(fields=['branch', 'session', 'term'], name='attendance__branch__80e80c_idx')],
                'unique_together': {('branch', 'session', 'term')},
            },
        ),
    ]
